-- Run this in your Supabase SQL Editor to create the season 6 trade posts table

CREATE TABLE IF NOT EXISTS season6_trade_posts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    alliance_name TEXT NOT NULL,
    server_number INTEGER NOT NULL,
    trade_posts_count INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Disable Row Level Security (RLS)
-- Since the application uses Stack Auth instead of Supabase Auth, client-side requests are sent using 
-- the anonymous public client. This means auth.uid() is not populated in Supabase.
-- Role verification (R4/R5) is handled at the application layer.
ALTER TABLE season6_trade_posts DISABLE ROW LEVEL SECURITY;
